Classes = [
    {
        "cid": "{c9ae7ee3-ce69-4fcb-b7e7-b4478b8d84b3}",
        "contract_ids": [
            "@mozilla.org/network/protocol/about;1?what=eqsat",
        ],
        "interfaces": ["nsIAboutModule"],
        "esModule": "resource:///modules/about_eQsat.sys.mjs",
        "constructor": "About_eQsat",
    },
    {
        "cid": "{d2435a88-326f-4b43-9be9-abf64dc41715}",
        "contract_ids": ["@mozilla.org/eqsat/command-line-handler;1"],
        "interfaces": ["nsICommandLineHandler"],
        "esModule": "resource:///modules/eQsatCommandLine.sys.mjs",
        "constructor": "eQsatCommandLineHandler",
        "categories": {
            "command-line-handler": "e-eqsat"
        }
    },
]