#ifndef CENONETWORKCLIENT_RESOURCE_H
#define CENONETWORKCLIENT_RESOURCE_H

#define IDS_TOOLTIP_CONNECTING  100
#define IDS_TOOLTIP_DEGRADED    101
#define IDS_TOOLTIP_CONNECTED   102
#define IDS_TOOLTIP_EXITING     103
#define IDS_TOOLTIP_RESTARTING  104
#define IDS_TOOLTIP_OFFLINE     105

#define IDC_CONTEXTMENU         209
#define IDM_EXIT                210
#define IDM_OPEN                211

#define IDI_ICON_ACTIVE             150
#define IDI_ICON_GRAY               151

#endif //CENONETWORKCLIENT_RESOURCE_H
