Classes = [
    {
        "cid": "{8ba5eb7a-76fa-4d8a-a028-0aa8dfa1b5e1}",
        "interfaces": ["nsIOuinetNativeHelpers"],
        "contract_ids": [
            "@equalitie.org/ouinet-native-helpers;1",
        ],
        "type": "mozilla::OuinetNativeHelpers",
        "headers": ["OuinetNativeHelpers.h"],
        "js_name": "OuinetNativeHelpers",
    },
]