/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#ifndef mozilla_nsOuinetNativeHelpers_h__
#define mozilla_nsOuinetNativeHelpers_h__

#include <atomic>

// This will pull in the header auto-generated by the .idl file:
// {obj-directory}/dist/include/nsIComponentName.h
#include "nsIOuinetNativeHelpers.h"
#include "nsIObserver.h"
#include "nsIThread.h"

#if defined(XP_WIN)
#include <windows.h> // HANDLE typedef
#endif

// The implementation can be namespaced, while the XPCOM interface is globally namespaced.
namespace mozilla {

// Notice how the class name does not need to be prefixed, as it is defined in the
// `mozilla` namespace.
class OuinetNativeHelpers final : public nsIOuinetNativeHelpers, public nsIObserver {
  NS_DECL_ISUPPORTS
  NS_DECL_NSIOBSERVER
  NS_DECL_NSIOUINETNATIVEHELPERS

  nsCOMPtr<nsIThread> clientMonitorThread = nullptr;
  nsCOMPtr<nsIThread> firewallMonitorThread = nullptr;
  nsCOMPtr<nsIThread> networkStatusMonitorThread = nullptr;
  std::atomic<int32_t> udpPort;

#if defined(XP_WIN)
  HANDLE shutdownEvent = nullptr;
  HANDLE portUpdateEvent = nullptr;
#elif defined(XP_LINUX)
  int shutdownEvent[2] = {-1, -1};
  int portUpdateEvent[2] = {-1, -1};
#endif
  bool isRegistered = false;

 public:
  OuinetNativeHelpers();

 private:
  // A private destructor must be declared.
  ~OuinetNativeHelpers();
  void Shutdown();
};

}  // namespace mozilla

#endif
