Classes = [
    {
        "cid": "{8ba5eb7a-76fa-4d8a-a028-0aa8dfa1b5e1}",
        "interfaces": ["nsIMetricsGeoTimezone"],
        "contract_ids": [
            "@equalitie.org/metrics-geo-timezone;1",
        ],
        "type": "mozilla::MetricsGeoTimezone",
        "headers": ["MetricsGeoTimezone.h"],
        "js_name": "MetricsGeoTimezone",
    },
]